### ISSUE TITLE
サルワカを読んで HTML/CSS について復習

### ISSUE THREAD

**Issue by cat2koban** [cat2koban/Learn-HTML-CSS#1]
## やること
- [サルワカ](https://saruwakakun.com/html-css/basic) を読む
- 気になったコードを写経していく

**Comment by cat2koban** [comment]
## step 3

- HTML の基本
  - タグで挟む
  - タグの中身は `要素` と呼ばれる
  - 開始タグの中に，`属性` を書くこともある 
  - `head` の中身はページの情報
- p
  - 段落
- h*
  - h1 ~ h6 まで見出しレベルがある
- a
  - リンク
  - `href` 場所
- img
  - `src` 場所
  - `alt` 代替テキスト, 画像が読み込めなかったときに表示するテキスト
- ul, ol, li 
  - `li` 箇条書きの要素
  - `ul` 箇条書きがぽっち
  - `ol` 箇条書きが数字
- br
  - 改行
  - 慣れてくると使わない
- 
  - コメントアウト
- id, class
  - `id` 1つのHTML文書内で同じid名を使うことができない
  - `class` 何回でも同じclass名を使うことができる
- div, span
  - まとまりを作るときに使う
  - div
    - 前後に改行が入る `ブロック要素`
  - `span` 
    - 前後に改行が入らない `インライン要素`
    - 文章中の文字色を変えたりするときに使う

**Comment by cat2koban** [comment]
## step 4

- CSS の基本
  - `style` タグを追加
    - 別ファイルでも可
- 書き方
  ```CSS
  セレクタ: {
    プロパティ: 値;
  }
  ```
  - 例: body タグの文字色を red に
  ```CSS
  body: {
    color: red;
  }
  ```
- セレクタの書き方
  - タグ { ... }
  - #id名 { ... }
  - .class名 { ... }
  - ○○, ○○, ○○ { ... }
    - 複数指定
  - .main p span { ... }
    - 子孫指定
    - main クラス内の p タグ内にある span タグ
- font-size
  - 文字の大きさ
  - px
    - 縦のピクセルの大きさで指定
  - em
    - 現在のフォントサイズに対する倍率
    - 10px の時， 2em だと, 20pxになる
- color 
  - 色指定
  - カラーコード指定
- text-align
  - left
    - 左寄せ
  - center
    - 中央寄せ
  - right
    - 右寄せ
- background-color
  - 背景色
- border
  - 指定項目が意外と多い
  - セレクタ { border: 線の種類 太さ 色 }
  - 線の種類
    - solid (実線)
    - dotted (点線)
    - dashed (破線)
    - double (二重線)
  - 太さ
  - 色
  - `border: none` とすると線なし **デフォルト**
  - 上にだけ線を引く：border-top:〜
  - 下にだけ線を引く：border-bottom:〜
  - 左にだけ線を引く：border-left:〜
  - 右にだけ線を引く：border-right:〜
- /* */
  - コメントアウト

**Comment by cat2koban** [comment]
## step 5

- width
  - 要素の横幅を決めるもの
- height
  - 要素の高さを決めるもの
- `display: inline` だと，幅，高さは指定できない
<img width="685" alt="スクリーンショット 2019-08-10 14 12 40" src="https://user-images.githubusercontent.com/10192563/62817874-f442d100-bb78-11e9-8531-c86ebe9dad7a.png">引用元 : https://saruwakakun.com/html-css/basic/width-height

- **width**
  - 覚えておきたい値
    - `width: auto` **default**
    - width: ○px;
    - width: ○%;
  - width: auto とは
    -  display: block
        p, div, 見出しなどは，何も指定がないと横いっぱいに広がっている (親要素が td, flex を除く)
    -  display: inline`やinline-block
        要素の幅＝要素の中身（テキスト）の長さとなる，親要素以上に自動で大きくなることはない
  - 子要素の幅を親要素の幅より大きくしてはいけない
  - width: 100% とすると，親要素と同じ幅になる
  - with: 100% と with: auto の違い
    - with: 100% padding, border の分が含まれない
    - with: auto padding, border の分が含まれる
  - display:inline-blockにした要素を横いっぱいに広げたい場合には、width:100%を指定する必要がある
  - inline の要素にはそもそも幅指定できない
  - 横並びの要素の幅を均等にしたい場合，%が便利
- **height**
  - 覚えておきたい値
    - `height: auto` **default**
    - height: ○px;
    - height: ○%;
  - height: auto
    - 基本的には，要素の中身の高さになっている
  - height: ○%;
    - 親要素のheightが指定されていないと、%指定はできない
  - 画面の半分の高さにしたい時
    - 全てのhtmlとbodyタグに対してheight:100%と指定
    - bodyの直下の要素をheight:50%

**Comment by cat2koban** [comment]
## step 6

- min-width
  - 指定値より小さくならないように
- max-width
  - 指定値より大きくならないように
- 縦横比が崩れたら， height: auto

**Comment by cat2koban** [comment]
## step 7
- padding
  - 要素の内側の余白
  - 背景色は padding まで含められる
  - border を追加すると, padding の外側に枠線が表示される
  - 画像の背景も同じ，padding まで含められる, borderも
- margin
  - 要素の外側の余白
- `margin|padding: 上 右 下 左`
- `margin|padding: 上下 左右`
- border は %指定できない
- 適用されるmarginは値が大きい方
- display: blockの要素のみ，margin-right|left: auto で水平方向に中央寄せが可能

**Comment by cat2koban** [comment]
## step 8
- displayとは?
  - 要素の表示形式を決めるもの
  - block
  - inline
  - inline-block
  - none
  - タグごとに display の初期値が決まっている
  - https://saruwakakun.com/html-css/basic/display

**Comment by cat2koban** [comment]
## step 9
- font-weight: bold
  - 太字
- font-style: italic
  - 斜文字
- line-height
  - 行間
  - おすすめは 1.5 ~ 2
- lettar-spacing
  - 文字の間隔
  - おすすめは 0.05 ~ 0.1em
- text-decoration
  - underline
    - 下線
  - line-through
    - 取り消し線
- font-family
  - フォントの種類の変更
- 1部の文字だけ設定を変える方法
  - `<span style=”下線のCSSコード”>下線を引きたい文字</span>`
  - 文字をclass名のついたspanタグではさむ⇒CSSで設定を書く

**Comment by cat2koban** [comment]
## step 10
- 端末によってみることのできるフォントが変わる => フォントは複数指定が基本
- 前に書かれたフォントが優先される
- 英語フォントを前に書く
- 最後に総称フォントファミリーを書く
  - 最後の砦
  - どれも適用できなかったときに，せめてこれにしてっていう最後の砦
  - sans-serif か serif
- おすすめのフォント指定
```CSS
body {
font-family: 'Avenir','Helvetica Neue','Helvetica','Arial','Hiragino Sans','ヒラギノ角ゴシック',YuGothic,'Yu Gothic','メイリオ', Meiryo,'ＭＳ Ｐゴシック','MS PGothic'  
}
``` 
- https://saruwakakun.com/font-family
  - 書く環境に対応しているフォントの種類が載っている

**Comment by cat2koban** [comment]
## step 11
- a
  - href 
    - url
  - target
    - _blank にすると別タブで開く
- `<a><img /></a>`
  - 画像がボタンに
- `a {text-decoration: none}`
  - リンクの下線を消す
- `a {color: 色コード or 色名}`
  - リンクの色を変える
- `a:hover {〜}`
  - カーソルが上にのった時の色を変える
- `a:hover img {〜}` 
  - カーソルが上にのった時の画像の色を変える
- `a:visited {〜}`
  - 訪問済みのリンクの色を変える
-

**Comment by cat2koban** [comment]
## step 12 
- font-awesome とは
  - http://fontawesome.io/
  - web アイコンフォントを表示してくれるサービス
- CDN を使ったり, asset/ としてサーバーに置いたりして使う
- アニメーションも多数クラス名を追加するだけで実装できるみたい
  - Font Awesome Animation

**Comment by cat2koban** [comment]
## step 13
- Unordered List (順序のない箇条書き)
- Ordered List (順序ありの箇条書き)
- リストデザイン 34選
  https://saruwakakun.com/html-css/reference/ul-ol-li-design
- `ul {list-style-type: square}`
  - ポチが四角形になる
- `ol{list-style-type: upper-latin}`
  - 番号を英語に
- `ul {list-style-type: none}`
  - ポチを消す
- 箇条書きの余白とインデント調整方法
  - https://saruwakakun.com/html-css/reference/list-space
- リストはネストできる

**Comment by cat2koban** [comment]
## step 14
- positionとは？どんな時に使う？
  - position
    - 要素の位置を決めるプロパティ
    - 要素を指定した分だけ動かしたり
    - 要素の上に別の要素を重ねたり
    - 常に画面の同じ位置に固定したりできる
  - 基本的な書き方
    - `〇〇{position: 値}`
  - position の値
    - static：初期値はこれ。指定することはほとんどない
    - relative：現在の位置を基準に相対的な位置を決める
    - absolute：親要素を基準に絶対的な位置を決める
    - fixed：画面のきまった位置に固定する
- position とセットで使う top・bottom・left・right
  - 位置を指定する流れ
    1.  position で基準を決める
    2.  top, bottom, left, right で具体的な数字で位置を決める
  - `top` や `left`, `bottom` や `right` といった組み合わせてよく使われる
- staticの使い方
  - static とは
    - 初期値：CSSで何も指定していなければコレになっている
    - 要素は通常の位置に：上下左右に動かすことができない
    - 要素の位置を調整できない：topやleftなどを指定しても効かない
    - z-indexを指定できない：要素の重なり順を変えられない
  - 位置を変えたい時は `relative` や `absolute` を使おう
- relativeの使い方
  - 現在の表示位置から相対的に要素の位置を動かしたいときに使う
  - z-indexやtopなどが指定できないときはrelativeにする
- absoluteの使い方
  - 親要素を基準に、絶対的な位置を指定することになる
  - absoluteを使って位置調整するときは、親要素に `position:relative|fixed` を指定する
- fixedの使い方
  - 画面の決まった位置に要素を固定させたいときに使う

**Comment by cat2koban** [comment]
## step 15
- z-index
  - 要素の重なり順を指定するCSSのプロパティです。
  - 基本的な書き方
  ```CSS
  セレクタ {
    z-index: 数字;
  }
  ```
  - z-index: 数字 で指定した値が大きいほど上|前に来る
  - position: absolute|fixed により要素が重なっているときに使う
- z-index が使えない時の対処法
  - `position: static` の要素には使えない
  - 値は整数のみ

**Comment by cat2koban** [comment]
## step 16
- カーソルの形状を変える方法
  - CSS の `cursor` で変える
  - 基本的な書き方
  ```CSS
  ◯◯ {cursor: 値;}
  ```
- 値の一例，サンプルコード 
  https://saruwakakun.com/html-css/basic/cursor

**Comment by cat2koban** [comment]
## step 17
- `overflow` とは
- 基本的な書き方
  ```
  ◯◯ {overflow:値;}
  ```
- 値
  - visible：初期値。はみ出た部分が、はみ出たままの状態で表示される場合あり
  - hidden：はみ出た部分が隠れる
  - scroll：はみ出た部分が隠れてスクロールできる状態に
  - auto：ブラウザにより表示が変わる（基本的にはスクロールできる状態に）

**Comment by cat2koban** [comment]
## step 18
- white-spaceとは？
  - HTMLコード内の半角スペース、タブ、改行をブラウザでどのように表示させるかを決めるプロパティ
  - 基本的な書き方
  ```
  ◯◯ {white-space: 値;}
  ```
- 値 
  - :normal
    - 初期値
    - 連続した改行や半角スペースは1つの空白にまとめられる
    - 要素の右端で行が折り返し
    - 文末の半角スペースや改行、tabなどは基本的に無視される 
  - :nowrap
    - 行が折り返されない
  - :pre-line
    - 連続した半角スペースやtabは1つの空白にまとめられる
    - HTMLコード内の改行はそのまま反映される
  - :pre
    - HTML内の改行や半角スペースがブラウザ表示にそのまま反映される
    - 自動で行が折り返されることはない
  - :pre-wrap
    - 改行や半角スペースがブラウザ表示にそのまま反映
    - 要素の端で行が折り返される

**Comment by cat2koban** [comment]
## step 19
- h1 ~ h6 まで見出しタグがある
- h1 はサイトタイトルなど
- h2 は記事タイトルなど
- h3 は記事中の中見出しなどに
- **重要**
  - h1 ~ h6 まで使う順番を守る
  - h1 の使用は一回まで
  - 見出しタグだけで記事を作らない
  - 基本的に見出しに画像を使わない
  - キーワードを無理に詰め込まない
  - h1 ~ h6 タグは，強調のために使うのではなく，見出しのために使いましょう
- おしゃれな見出し68選 多い笑
  - https://saruwakakun.com/html-css/reference/h-design

**Comment by cat2koban** [comment]
## step 20
- div と span の意味
  - divとは span とは
    - どちらもHTMLのタグ
    - タグ自体に意味はない
    - pタグ：段落を表す
    - h1タグ：大見出しを表す
    - ulとliタグ：箇条書きを表す
    - divタグ：何も表さない
    - spanタグ：何も表さない
- 2つの違い
  - div : block
  - span : inline
  - 幅と高さを指定できるかどうか
  - 前後に改行が入るかどうか
  - spanは文字の装飾などに便利
  - spanの中にdiv入れない
- **divはあらゆるものを挟んで大きなまとまりを作る**
- **spanは小さい（主に文字）まとまりを作る**
- 2つともなるべく使う回数を減らす

**Comment by cat2koban** [comment]
## step 21
- 基本的な使い方
  - table：表全体をはさむ。<table>〜</table>の範囲が表となる。
  - tr：Table Rowの略。行全体をはさむ。いくつ使ってもOK。
  - th：Table Headerの略。trの中で使う。はさまれた部分は見出しセルとなる。
  - td：Table Dataの略。trの中で使う。はさまれた部分が表の中身のセルとなる。いくつ使ってもOK。
- `rowspan` で縦方向につなげる
- `colspan`  で横につなげる
- 表の幅を変えるには `table {witdh: ~}` と指定してあげる
- [CSSでできるレスポンシブ対応を考えた table レイアウト](https://www.unionnet.jp/blog/responsive-table-css/)

**Comment by cat2koban** [comment]
## step 23
- [Google Fonts](https://fonts.google.com/)
  - ユニークでオサレなwebサイトに見せることができる
  - `オサレ == 読みやすい` ではない

**Comment by cat2koban** [comment]
## step 24
- `::after`, `::before`
  - HTMLには書かれていない要素もどきをCSSで作ることができる
- こうやって書くこともできる。 https://codesandbox.io/s/agitated-germain-uzo8j
  ```CSS
  h1 {
    position: relative;
    padding: 1em; /* 要素内の余白 */
    background: silver; /*背景色*/
  }
  h1:before { /*擬似要素*/
    position: absolute;
    content: 'ラベル';
    top: 0;
    left: 0;
    color: white; /*文字色*/
    padding: 0.2em; /*余白*/
    background: #F89174; /*背景色*/
  }
- それらしく引用ブロックも作れる
  https://saruwakakun.com/html-css/reference/blockquote
- `hoge:before { content: url(../img/saruwakakun.png) }` とすると擬似要素として画像を表示できる

**Comment by cat2koban** [comment]
## step 25
- 要素を中央配置する方法
  - 文章
  ```CSS 
  text-align: center;
  ```
  - 画像
  ```CSS
  親 {
    text-align: center; 
    img { ... }
  }
  ```
  - この2つは忘れやすそう。
    - **ブロックの要素にtext-alignを使っても中央寄せにならない**
    - **インラインの要素にはCSSで幅を指定しても意味がない**
  - ちょっと複雑な`inline-block` もあるよ
    - **ブロックのように幅指定もできますし、インラインのようにtext-align指定もできる**
  - **ブロックの要素をinline-blockに変えてから、親にtext-align:centerを使えば簡単に中央寄せできる**
- 縦センタリング
  - 1行の場合 `行の高さ＝親要素の高さ` とするだけでもセンタリングできる
  - 2行以上の場合
    - **親要素に `position:relative` を指定しておく**
    - センタリングしたい要素を絶対配置 `position:absolute` に
    - `top: 50%` で親要素から上から `50%` の位置に
    - `transform: translateY(-50%)` でズレを補正
  - 親要素のど真ん中に配置
  ```CSS
  親要素には position: relative;
  absolute + top: 50% + left: 50% + transform: translate(-50%,-50%)
  ``` 
- flexbox を使った中央寄せもあるみたい
  - そもそもなにそれ？
    - サイズの異なる要素を、柔軟かつ簡単に綺麗に並べてくれるCSS3の機能
- 画像の上に配置したい場合
  - https://saruwakakun.com/html-css/reference/image-text
- 円のど真ん中に配置したいとき
  ```
  - 1行以内の文字なら line-height を円の height に合わせる
  - 2行以上になりそうなら absolute を活用
  ```
- **中央寄せができない時の対処方法**
  - text-align:centerが効かない
    - ブロック要素になっていませんか？
    - 親要素に対して指定していますか？
  - margin: 0 autoが効かない
    - インライン要素になっていませんか？
    - 親要素の幅が小さくなっていませんか？
  - position: absoluteができない
    - 親要素はrelativeになっていますか？

**Comment by cat2koban** [comment]
## step 26
- CSS でグラデーションかけたい時
```CSS
  background: liner-gradient(ここに色を指定);
  例：body { background:linear-gradient(#F89174, #FFC778); }
```
  - liner
    - 線状のグラデーション
  - radial
    - 円状のグラデーション
- 95% のブラウザで対応されている
- ベンダープレフィックスはつけておこう
  ```CSS
  ○ ○ {
    background: -moz-linear-gradient(~);
    background: -webkit-linear-gradient(~);
    background: linear-gradient(~); 
  }
  ```
- **通常の書き方とベンダープレフィックス付きの書き方が微妙に異なる**
  -  上から下にグラデーション
  ```CSS
  {
    background: -moz-linear-gradient(top, #FFC778, #FFF);
    background: linear-gradient(to bottom, ##FFC78, #FFF);
  }
  ```
- 横向きのグラデーションも同様
- カラーコードの後ろに `x%` とすると，x~100% までがグラデーションになる
- 斜めのグラデーションとなると
  - 開始位置で
    - `-moz-linear-gradient(top left, #FFF, #000);` という風に，`左上から` と指定する
    - 通常は，`linear-gradient(to bottom rigtht, #FFF #000)+` という風に書く
    - 開始位置で斜めのグラデーションをかけると，斜め具合を調整することはできない。45度に統一される。
  - 角度で
    - `background: linear-gradient(25deg, #FFF, #000);` とかく
    - 0: 下から上
    - 45: 左下から右上
    - 90: 左から右
    - 180: 上から下
    - ベンダープレフィックスをつける場合
      - `ベンダープレフィックス付きのdeg = 90 - 通常のdef` となる
    - 通常の書き方で 25deg とすると，90 - 25 - 65 になる。
- radial-gradient 円状のグラデーション
  ```CSS
  #sample {
    background: -moz-radial-gradient(#FFF, #000);
    background: radial-gardient(#FFF, #000);
  }
  ```
- かっこの初めに ` 中央の色` ，カンマで区切って `外側の色`
- 片側を透明にしたい transparent を指定
  ```css
  #sample {
    background: -moz-linear-gradient(top, #FFC778, transparent);
    background: -webkit-linear-gradient(top, #FFC778, transparent);
    background: linear-gradient(to bottom, #FFC778, transparent);
  }
  ```
 - 半透明の場合，`rgba(255, 0, 0, 0.1)` としてあげる
- `10. グラデーションサンプルが見つかるサイト` いくつかあるみたい
- [CSSで背景グラデーション+アニメーションで変化する背景色](http://weblifetimes.com/css-gradietion-animetion/)

**Comment by cat2koban** [comment]
## step 27
- 基本的なデザインの パンくずリスト
- https://codesandbox.io/s/pankuzurisuto-p82eg

**Comment by cat2koban** [comment]
## step 28
- `opacity` で画像や文字などを透過させる
- 基本的な書き方
```css
  ○○ {
    opacity: 透過度;
  }
```
- 透過度
  - 0: 完全透明
  - 0.5: 50%透明
  - 1: 不透明(= 何も指定しなかった場合)
- ベンダープレフィックスをつける必要はあ基本的にない
- 例
```css
/*ゆっくり透明に*/
.example img {
  transition: .3s;
}

/*ホバー時に透明度50%*/
.example img:hover {
  opacity: 0.5;
}
```
- `transition: .3s` は，ホバー時の変化を滑らかにするもの

**Comment by cat2koban** [comment]
## step 29
- cssで円を描くには
- 基本的な書き方
```css
セレクタ {
  width: ○○px; /* 幅 */
  height: ○○px; /* 高さ */
  border-radius: 50%; /* 角丸 */
}
```
- `span` や `a` タグは，初期設定で `display: inline` となっているため，幅と高さを指定できない。円形にしたい時は，`inline-block` にしてあげよう
- 円の中心に文字を乗せる方法
  - 文章が1行の場合
    - `text-alilgn: center`
    - `line-height: 80px`
  - 2行の場合
    - 親要素を `position: relative;` に
    - 子要素を `position: absolute;` に
    - HTMLでは円と文字を分ける
- 円を枠線にしたい
  - `border: solid ○px #color` にするだけ
  - あとは border のオプション次第で点線だったり色々
- 円を親要素の左右中央に配置する方法
  - block 要素だと，`margin: 10px auto;` なりで良い
  - inline-block だと， 親要素の `text-align` を center にするだけで良い

**Comment by cat2koban** [comment]
## step 30
- 影
- 基本的な書き方
```css
セレクタ {
  box-shadow: 左右の向きpx 上下の向きpx ぼかしpx 広がりpx 色 内側指定;
}
```
- ぼかしのない影
  - `box-shadow: 4px 4px;`
  - 1つめの値: 左右の方向指定
  - 2つめの値: 上下の方向指定
  - 負の値にすると
- 影の色を変える
  - `box-shadow: 6px 6px #668AD8;`
  - 3番目にカラーコードを書く！
- 影をぼかす
- 結構サンプルが多いみたい
  - https://saruwakakun.com/html-css/basic/box-shadow
